### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by randomdev4578** [Strawberry-Software-Industries/SecureCloud#4]
![image](https://user-images.githubusercontent.com/85356882/151660140-c2c38af9-1bbb-42d6-8814-444c93ea28c2.png)
that should say everything.

OS: Raspberry Pi OS 11 (Bullseye)
Python Version: 3.10.2
SecureCloud Build: v1.0

**Comment by Juliandev02** [comment]
You have to delete the users.db in your DB folder. 
Otherwise wait for the new SecureCloud release, because there the DB is rebuilt.
