### ISSUE TITLE
[FEATURE REQUEST] Encrypt files

### ISSUE THREAD

**Issue by ghost** [Strawberry-Software-Industries/SecureCloud#6]
Add a feature where you can encrypt files that are only read/writeable via SecureCloud. When downloading/viewing/modifying a file, you have to be logged in as the user that uploaded the file.

**Comment by Juliandev02** [comment]
It's a good idea in principle, but unfortunately I have no idea about decryption of files. If you have time & desire, you can always contribute, and create a pull request (as a developer you can also upload the changes so, but can also do it via pull request)!

**Comment by Juliandev02** [comment]
This feature will be implemented soon!

**Comment by ghost** [comment]
This will be a Pro Home exklusive feature.
