### ISSUE TITLE
Fix code scanning alert - Clear-text logging of sensitive information

### ISSUE THREAD

**Issue by ghost** [Strawberry-Software-Industries/SecureCloud#7]
Tracking issue for:

- [x]  https://github.com/Strawberry-Software-Industries/SecureCloud/security/code-scanning/13 (13)
~~https://github.com/Strawberry-Software-Industries/SecureCloud/security/code-scanning/12 (12)~~
~~https://github.com/Strawberry-Software-Industries/SecureCloud/security/code-scanning/11 (11)~~

**Comment by Juliandev02** [comment]
I fixed https://github.com/Strawberry-Software-Industries/SecureCloud/security/code-scanning/13

**Comment by Juliandev02** [comment]
See commit https://github.com/Strawberry-Software-Industries/SecureCloud/commit/543d0789ffaf7422a336b605ca703186c9008315

**Comment by ghost** [comment]
> See commit [543d078](https://github.com/Strawberry-Software-Industries/SecureCloud/commit/543d0789ffaf7422a336b605ca703186c9008315)

Waiting for the CodeQL

**Comment by ghost** [comment]
Done, see: https://github.com/Strawberry-Software-Industries/SecureCloud/security/code-scanning/13
